name=esp32-Encrypt
version=1.0.2
author=schmitta38 <schmitta38@noreply.github.com>
maintainer=schmitta38 <schmitta38@noreply.github.com>
sentence=Encryption library for ESP32
category=Other
url=https://github.com/schmitta38/esp32-Encrypt
architectures=esp32
includes=Cipher.h
